import type { Metadata } from "next";import { LegalShell,type LegalSection } from "@/app/legal-shell";
export const metadata:Metadata={title:"Privacy Policy | VXL",description:"How VXL collects, uses, stores and shares information.",alternates:{canonical:"/privacy"}};
const sections:LegalSection[]=[
{title:"Information We Collect",paragraphs:["Depending on how you use VXL, we may collect account information, profile and user content, plan and transaction information, technical and usage information, and communications."],bullets:["Account information: name, email address, authentication/account information and account identifiers.","Profile and user content: information you voluntarily provide; content created, uploaded or stored through VXL; preferences and settings.","Plan and transaction information: selected plan; transaction/reference identifiers; payment and activation status; purchase and access-expiry dates; billing-related information necessary to maintain transaction records.","Technical and usage information: device/browser information; IP address where collected by our infrastructure or service providers; timestamps; pages/features used; diagnostic, security, usage and performance data.","Communications: support requests, emails or messages sent to VXL, feedback and other communications."]},
{title:"Payment Information",paragraphs:["Payments may be processed by third-party payment processors such as Razorpay.","Sensitive payment credentials such as complete card numbers, UPI PINs or banking passwords are processed by the relevant payment provider and are not intended to be stored directly by VXL.","We may receive transaction information such as payment status, amount, transaction identifiers and payment timestamps where necessary to provide paid Services and maintain records."]},
{title:"How We Use Information",paragraphs:["We may use information to:"],bullets:["provide and operate VXL;","create and manage accounts;","provide requested features;","process and verify plan purchases;","maintain payment and plan-access records;","send transactional and service-related communications;","provide customer support;","prevent fraud and abuse;","maintain security;","diagnose technical problems;","understand and improve product performance;","comply with legal obligations."]},
{title:"Legal and Operational Basis",paragraphs:["We process information where necessary to provide the Services requested by users, operate our business, protect our Services, comply with applicable legal requirements, and where applicable based on user consent."]},
{title:"Service Providers",paragraphs:["VXL may use trusted service providers for hosting and infrastructure, databases, authentication, email delivery, analytics, payment processing, security and monitoring.","These providers may process information as necessary to perform services for VXL and are subject to their own contractual and legal obligations."]},
{title:"Information Sharing",paragraphs:["VXL does not sell users' personal information.","Information may be shared:"],bullets:["with service providers necessary to operate VXL;","when requested or authorised by the user;","where required by law, regulation or valid legal process;","where reasonably necessary to prevent fraud, abuse or security threats;","in connection with a legitimate business restructuring, acquisition or transfer, subject to applicable law."]},
{title:"Data Retention",paragraphs:["We retain personal information for as long as reasonably necessary to provide the Services, maintain legitimate business and transaction records, resolve disputes, prevent fraud and comply with legal obligations.","Different categories of information may have different retention periods."]},
{title:"Security",paragraphs:["We use reasonable technical and organisational safeguards designed to protect information against unauthorised access, alteration, loss or misuse.","No internet-based service can guarantee absolute security, and users should also protect their account credentials."]},
{title:"User Rights and Choices",paragraphs:["Depending on applicable law, users may have rights regarding access, correction, deletion or other processing of their personal information.","Requests can be submitted through the VXL Contact Us page. Certain information may need to be retained where required for legal, accounting, fraud-prevention or legitimate operational purposes."]},
{title:"Cookies and Similar Technologies",paragraphs:["VXL may use cookies, local storage or similar technologies required for authentication, security, preferences, functionality and analytics.","Where legally required, additional consent mechanisms may be provided for non-essential technologies."]},
{title:"Children's Privacy",paragraphs:["VXL is not intended to knowingly collect personal information from children in circumstances where parental or guardian consent is legally required.","If we become aware that information has been collected contrary to applicable law, we will take appropriate steps to address it."]},
{title:"International Processing",paragraphs:["Some technology providers used by VXL may process or store information in locations outside the user's country.","Where applicable, VXL and its providers will handle such processing in accordance with applicable data-protection requirements."]},
{title:"Changes to this Policy",paragraphs:["We may update this Privacy Policy as our Services, technology or legal obligations change.","The latest version will be published on this page with the effective date."]},
{title:"Contact",paragraphs:["Privacy questions and requests can be submitted through the VXL Contact Us page or by emailing hello@thevxl.com."]}];
export default function PrivacyPage(){return <LegalShell title="Privacy Policy" intro={["VXL respects your privacy. This Privacy Policy explains how information may be collected, used, stored and shared when you use thevxl.com and related VXL Services."]} sections={sections}/>}
