import Link from "next/link";

export type LegalSection = { title: string; paragraphs?: string[]; bullets?: string[] };

export function LegalShell({ title, effective = "Effective Date: 9 September 2026", intro, sections }: { title: string; effective?: string; intro: string[]; sections: LegalSection[] }) {
  return <main className="min-h-screen bg-[#f5f5f7] text-[#111113]"><header className="sticky top-0 z-20 flex h-16 items-center justify-between border-b border-black/10 bg-white/85 px-5 backdrop-blur-xl md:px-12"><Link href="/" className="flex items-center gap-2 font-extrabold tracking-[-.05em]"><span className="grid h-8 w-8 place-items-center rounded-lg bg-gradient-to-b from-zinc-600 to-black text-white shadow-lg">X</span>VXL</Link><Link href="/" className="text-xs font-semibold text-zinc-500 hover:text-black">Back to VXL</Link></header><article className="mx-auto max-w-3xl px-5 py-14 md:py-20"><p className="text-[11px] font-bold tracking-[.18em] text-zinc-500">VXL · LEGAL</p><h1 className="mt-4 text-4xl font-bold tracking-[-.055em] md:text-6xl">{title}</h1><p className="mt-5 inline-flex rounded-full border border-black/10 bg-white px-3 py-1.5 text-xs text-zinc-600">{effective}</p><div className="mt-10 space-y-5 text-[15px] leading-7 text-zinc-600">{intro.map((p) => <p key={p}>{p}</p>)}</div><div className="mt-12 space-y-10">{sections.map((section, index) => <section key={section.title} className="border-t border-black/10 pt-8"><h2 className="text-xl font-bold tracking-[-.025em]"><span className="mr-3 text-zinc-400">{index + 1}.</span>{section.title}</h2><div className="mt-4 space-y-4 text-[15px] leading-7 text-zinc-600">{section.paragraphs?.map((p) => <p key={p}>{p}</p>)}{section.bullets && <ul className="list-disc space-y-2 pl-5">{section.bullets.map((item) => <li key={item}>{item}</li>)}</ul>}</div></section>)}</div></article><LegalFooter/></main>;
}

export function LegalFooter(){return <footer className="border-t border-black/10 bg-[#0b0b0d] px-5 py-10 text-zinc-400"><div className="mx-auto flex max-w-5xl flex-col justify-between gap-6 md:flex-row"><div><strong className="text-white">VXL</strong><p className="mt-2 text-xs">We Excel. We Grow Together.</p></div><nav className="flex flex-wrap gap-x-5 gap-y-3 text-xs"><Link href="/terms">Terms &amp; Conditions</Link><Link href="/privacy">Privacy Policy</Link><Link href="/refund-policy">Refund &amp; Cancellation Policy</Link><Link href="/contact">Contact Us</Link></nav><small>© 2026 VXL. All rights reserved.</small></div></footer>}
