type PreviewData = { fullName: string; headline: string; professionalSummary: string; theme: string; experiences: Array<{ id: string; role: string; company: string }>; items: Array<{ id: string; itemType: string; title: string }> };

const sampleSkills = (data: PreviewData) => data.items.filter((item) => item.itemType === "skill").slice(0, 6);

export function PortfolioMiniPreview({ data }: { data: PreviewData }) {
  if (data.theme === "canvas") return <div className="min-h-[620px] bg-[#07111f] p-7 text-white"><div className="h-px bg-white/15" /><p className="mt-9 text-[11px] font-bold uppercase tracking-[.2em] text-cyan-300">{data.headline || "Professional headline"}</p><h2 className="mt-4 text-4xl font-semibold leading-none tracking-[-.055em]">{data.fullName || "Your name"}</h2><p className="mt-6 text-sm leading-6 text-slate-300">{data.professionalSummary || "Your professional story will appear here."}</p><div className="mt-8 rounded-3xl bg-white p-5 text-slate-950"><p className="text-[10px] font-bold uppercase tracking-[.2em] text-indigo-600">Experience</p>{data.experiences.slice(0, 2).map((row) => <div key={row.id} className="mt-4"><p className="text-sm font-semibold">{row.role || "Role"}</p><p className="text-xs text-slate-500">{row.company || "Company"}</p></div>)}</div><div className="mt-5 flex flex-wrap gap-2">{sampleSkills(data).map((skill) => <span key={skill.id} className="rounded-full bg-white/10 px-3 py-1.5 text-xs">{skill.title}</span>)}</div></div>;
  if (data.theme === "ledger") return <div className="grid min-h-[620px] grid-cols-[120px_1fr] bg-white text-[#132238]"><div className="bg-[#12233f] p-4 text-white"><div className="grid h-12 w-12 place-items-center rounded-xl bg-amber-400 font-black text-slate-950">{(data.fullName || "YN").split(/\s+/).slice(0, 2).map((part) => part[0]).join("")}</div><p className="mt-5 text-xl font-semibold leading-tight">{data.fullName || "Your name"}</p><p className="mt-3 text-xs leading-5 text-slate-300">{data.headline || "Professional headline"}</p><p className="mt-8 text-[10px] font-bold uppercase tracking-[.16em] text-amber-300">Skills</p>{sampleSkills(data).map((skill) => <p key={skill.id} className="mt-3 border-b border-white/10 pb-2 text-[10px]">{skill.title}</p>)}</div><div className="p-5"><p className="text-[10px] font-bold uppercase tracking-[.18em] text-amber-600">Profile</p><p className="mt-4 text-xs leading-5 text-slate-600">{data.professionalSummary || "Your professional story will appear here."}</p><p className="mt-8 border-t border-slate-200 pt-5 text-[10px] font-bold uppercase tracking-[.18em] text-amber-600">Experience</p>{data.experiences.slice(0, 2).map((row) => <div key={row.id} className="mt-4"><p className="text-sm font-semibold">{row.role || "Role"}</p><p className="text-xs text-slate-500">{row.company || "Company"}</p></div>)}</div></div>;
  return <div className="preview-sheet"><div className="preview-accent" /><div className="p-7"><p className="text-xs font-semibold uppercase tracking-[.18em] text-indigo-600">Portfolio</p><h2 className="mt-6 text-3xl font-semibold tracking-[-.04em]">{data.fullName || "Your name"}</h2><p className="mt-2 text-base text-slate-500">{data.headline || "Your professional headline"}</p><p className="mt-6 text-sm leading-6 text-slate-600">{data.professionalSummary || "Your professional story will appear here."}</p><div className="mt-8 border-t border-slate-100 pt-6"><p className="preview-label">Experience</p>{data.experiences.slice(0, 2).map((row) => <div key={row.id} className="mt-4"><p className="text-sm font-semibold">{row.role || "Role"}</p><p className="text-xs text-slate-500">{row.company || "Company"}</p></div>)}</div><div className="mt-7"><p className="preview-label">Skills</p><div className="mt-3 flex flex-wrap gap-2">{sampleSkills(data).map((skill) => <span key={skill.id} className="rounded-full bg-slate-100 px-3 py-1.5 text-xs font-medium">{skill.title}</span>)}</div></div></div></div>;
}
