import type { Metadata } from "next";
import { LegalShell, type LegalSection } from "@/app/legal-shell";
export const metadata: Metadata = { title: "Terms & Conditions | VXL", description: "Terms governing access to and use of VXL.", alternates: { canonical: "/terms" } };
const sections: LegalSection[] = [
{title:"About VXL",paragraphs:["VXL is a digital platform that provides software-based tools, features and fixed-duration access plans to its users. Certain features may be available free of charge, while others require a one-time plan payment.","The features, pricing, limits and benefits associated with each plan are described on the VXL website and may be updated from time to time."]},
{title:"Eligibility",paragraphs:["You must be legally capable of entering into a binding agreement under applicable law to purchase paid Services.","If you use VXL on behalf of an organisation or another legal entity, you represent that you have authority to accept these Terms on its behalf."]},
{title:"Accounts",paragraphs:["Some VXL features may require an account.","You are responsible for:"],bullets:["providing accurate information;","maintaining the confidentiality of your account credentials;","activities conducted through your account; and","notifying VXL if you believe your account has been compromised.","You must not attempt to access another user's account without authorisation."]},
{title:"Plans and Fixed-Term Access",paragraphs:["VXL offers free access and paid digital-service plans. Current Live, Flex and Care purchases provide 28 days of access as a one-time payment and do not renew automatically.","The price, duration, available features, usage limits and any features marked Coming Soon are displayed before purchase.","Access to paid features is granted after successful payment confirmation and plan activation.","Unless explicitly stated otherwise at the time of purchase, purchasing a plan does not guarantee that every VXL feature will remain unchanged throughout the access period. We may improve, modify, replace or discontinue features where reasonably necessary."]},
{title:"Payments",paragraphs:["Payments for paid VXL Services may be processed through authorised third-party payment service providers, including Razorpay.","VXL does not directly store complete card details, UPI credentials or banking credentials provided to a payment processor.","By making a payment, you agree to provide accurate billing and payment information and comply with the applicable payment provider's terms.","A payment is considered successful only after VXL or its payment provider confirms successful processing."]},
{title:"Taxes",paragraphs:["Prices may be inclusive or exclusive of applicable taxes as indicated during purchase.","Where required by applicable law, taxes, duties or other statutory charges may be added to the amount payable."]},
{title:"Trial, Publishing and Expiry",paragraphs:["A user's seven-day free live period begins only when the portfolio is first published, not when the account or draft is created.","Publishing makes the approved portfolio version publicly accessible through its VXL link. Users remain responsible for reviewing the information they choose to publish.","A paid 28-day plan expires at the end of its stated access period unless the user makes a separate new purchase. Draft information remains saved subject to these Terms and the Privacy Policy, but an expired portfolio may no longer remain publicly accessible."]},
{title:"Acceptable Use",paragraphs:["You agree not to:"],bullets:["use VXL for unlawful, fraudulent or abusive purposes;","interfere with the security or operation of the Services;","attempt unauthorised access to VXL systems or accounts;","introduce malicious software or harmful code;","circumvent usage restrictions, plan controls or security measures;","scrape, copy or systematically extract VXL data except where expressly permitted;","impersonate another person or misrepresent your identity;","use the Services in a manner that infringes the rights of others.","We may restrict or suspend access where reasonably necessary to protect VXL, our users or third parties."]},
{title:"Intellectual Property",paragraphs:["VXL and its associated software, design, branding, interfaces, original content and technology are owned by or licensed to the operators of VXL and are protected by applicable intellectual-property laws.","Using VXL does not transfer ownership of VXL intellectual property to you.","Subject to these Terms, users receive a limited, non-exclusive, non-transferable and revocable right to use the Services for their intended purpose during the applicable access period."]},
{title:"User Content",paragraphs:["Where VXL allows users to submit, upload, create or store content, users retain ownership of their content.","You grant VXL the limited rights necessary to host, process, reproduce and display that content solely as reasonably required to provide and operate the Services.","You are responsible for ensuring that content you submit does not violate applicable law or third-party rights."]},
{title:"Availability and Changes",paragraphs:["We aim to provide reliable Services but do not guarantee uninterrupted or error-free availability.","VXL may occasionally be unavailable because of maintenance, updates, infrastructure failures, third-party service interruptions or circumstances outside our reasonable control.","We may update the Services to improve functionality, security or performance."]},
{title:"Third-Party Services",paragraphs:["VXL may rely on or integrate with third-party services, including hosting, authentication, databases, email infrastructure, analytics and payment processors.","Your use of certain third-party services may also be subject to their respective terms and privacy policies."]},
{title:"External Links and Content",paragraphs:["Portfolios may contain links or references supplied by users that lead to external websites, files or services. VXL does not control or endorse user-supplied external content and is not responsible for its availability, accuracy or practices.","Users should review external links before publishing them and ensure they have the right to share linked or embedded material."]},
{title:"Cancellation and Refunds",paragraphs:["Purchases, fixed-term access and refund requests are governed by the VXL Refund & Cancellation Policy available on our website."]},
{title:"Termination",paragraphs:["You may stop using VXL at any time.","VXL may suspend or terminate access where a user materially violates these Terms, abuses the Services, engages in fraudulent activity, creates security risks, or where suspension is otherwise required by law.","Where reasonably possible, we will take proportionate action based on the nature of the violation."]},
{title:"Disclaimer",paragraphs:["VXL is provided on an “as available” basis to the extent permitted by applicable law.","While we aim to maintain accurate and reliable functionality, we cannot guarantee that every feature will always operate without interruption or error.","Nothing in these Terms excludes rights or remedies that cannot legally be excluded under applicable consumer law."]},
{title:"Limitation of Liability",paragraphs:["To the maximum extent permitted by applicable law, VXL and its operators will not be liable for indirect, incidental, special or consequential losses arising from use of the Services.","Where liability cannot legally be excluded, it will be limited only to the extent permitted by applicable law."]},
{title:"Changes to These Terms",paragraphs:["We may update these Terms when our Services, business practices or legal obligations change.","The latest version will be published on this page with an updated effective date. Continued use of the Services after an update constitutes acceptance where permitted by applicable law."]},
{title:"Governing Law",paragraphs:["These Terms are governed by the laws of India. Any dispute will be subject to the jurisdiction of competent courts in India, subject to any mandatory rights or jurisdiction available to consumers under applicable law."]},
{title:"Contact",paragraphs:["Questions regarding these Terms can be submitted through the VXL Contact Us page or by emailing hello@thevxl.com."]}
];
export default function TermsPage(){return <LegalShell title="Terms & Conditions" intro={["Welcome to VXL. These Terms & Conditions (\"Terms\") govern your access to and use of the VXL website, services, features, tools, access plans and related digital products available through thevxl.com (\"Services\").","By accessing VXL, creating an account, purchasing a plan or otherwise using our Services, you agree to these Terms. If you do not agree with these Terms, please do not use the Services."]} sections={sections}/>}
