const escapeHtml = (value: string) => value.replace(/[&<>'"]/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" })[character] ?? character);

const SITE_URL = "https://www.thevxl.com";
const SUPPORT_EMAIL = "support@thevxl.com";

export function purchaseActivatedEmail(plan: string, purchaseId: string) {
  const text = `Your VXL ${plan} plan is active.\n\nOpen ${SITE_URL} to view your plan, expiry and usage allowances. No activation code is needed. This is a fixed-term purchase with no automatic renewal.\n\nPurchase: ${purchaseId}\nRazorpay sends your payment receipt separately.\nBilling questions: payments@thevxl.com`;
  return { subject: `Your VXL ${plan} plan is active`, text,
    html: shell(`Your VXL ${plan} plan is active.`, "PLAN ACTIVATED", `Welcome to ${escapeHtml(plan)}.`, `<p>Your payment has been verified and your plan is active. No activation code is needed.</p><p><a href="${SITE_URL}">Open your VXL dashboard</a> to see your expiry and usage allowances.</p><p>No automatic renewal. Razorpay sends your payment receipt separately.</p><p>Purchase: ${escapeHtml(purchaseId)}</p><p>Questions? <a href="mailto:payments@thevxl.com">payments@thevxl.com</a></p>`) };
}

type PlanEmailInput = { name: string; requestId: string; plan: string; cycle: string; amount: string; summary?: string; benefits?: readonly string[] };

const planBenefits: Record<string, readonly string[]> = {
  LIVE: ["One portfolio hosted on your VXL address", "Every template, palette, typeface and visual effect", "2 published updates and 1 résumé re-import every 28 days", "3 fact-checked AI writing improvements every 28 days", "Lifetime visit total and latest published version", "Small “Made with VXL” wordmark at the bottom"],
  FLEX: ["Everything included in Live", "Unlimited published updates and 5 résumé re-imports every 28 days", "30 fact-checked AI writing improvements every 28 days", "Detailed analytics and version history for 90 days", "No VXL wordmark on your portfolio", "Priority email support", "Custom-domain connection — coming soon"],
  CARE: ["Everything included in Flex", "10 résumé re-imports and 60 fact-checked AI improvements every 28 days", "Detailed analytics and version history for 1 year", "No VXL wordmark on your portfolio", "1 human-managed portfolio update every 28 days", "Personal priority help", "Guided custom-domain setup — coming soon"],
};

const safeBenefits = (input: PlanEmailInput) => input.benefits?.length ? input.benefits : planBenefits[input.plan.toUpperCase()] ?? [];
const benefitsText = (benefits: readonly string[]) => benefits.length ? `\nYour plan includes:\n${benefits.map((benefit) => `• ${benefit}`).join("\n")}\n` : "";
const benefitsHtml = (benefits: readonly string[]) => benefits.length ? `<div style="margin:24px 0 0;padding:20px;border:1px solid #e4e4e7;border-radius:14px;background:#fafafa"><div style="font-size:10px;line-height:1.4;letter-spacing:1.8px;color:#71717a;font-weight:800">YOUR PLAN INCLUDES</div><table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="margin-top:10px">${benefits.map((benefit) => `<tr><td style="width:18px;padding:7px 0;vertical-align:top;color:#09090b;font-size:11px">●</td><td style="padding:6px 0;color:#3f3f46;font-size:14px;line-height:1.55">${escapeHtml(benefit)}</td></tr>`).join("")}</table></div>` : "";

const logo = `<table role="presentation" cellspacing="0" cellpadding="0" border="0"><tr><td style="vertical-align:middle"><div style="width:31px;height:35px;border:1px solid #09090b;border-radius:16px 16px 1px 1px;padding:3px;box-sizing:border-box"><div style="height:27px;border:2px solid #09090b;border-radius:12px 12px 1px 1px;text-align:center;color:#09090b;font-size:17px;font-weight:200;line-height:34px">∞</div></div></td><td style="padding-left:10px;vertical-align:middle;color:#09090b;font-family:Arial,Helvetica,sans-serif;font-size:21px;font-weight:900;letter-spacing:-1.2px">VXL</td></tr></table>`;

const detailGrid = (input: PlanEmailInput) => `<table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="margin:24px 0 0;border-collapse:separate;border-spacing:0;border:1px solid #e4e4e7;border-radius:14px;overflow:hidden"><tr><td style="padding:15px 17px;border-bottom:1px solid #e4e4e7;color:#71717a;font-size:12px">Plan</td><td align="right" style="padding:15px 17px;border-bottom:1px solid #e4e4e7;color:#09090b;font-size:14px;font-weight:800">VXL ${escapeHtml(input.plan)}</td></tr><tr><td style="padding:15px 17px;border-bottom:1px solid #e4e4e7;color:#71717a;font-size:12px">Price</td><td align="right" style="padding:15px 17px;border-bottom:1px solid #e4e4e7;color:#09090b;font-size:14px;font-weight:800">${escapeHtml(input.amount)}</td></tr><tr><td style="padding:15px 17px;border-bottom:1px solid #e4e4e7;color:#71717a;font-size:12px">Access period</td><td align="right" style="padding:15px 17px;border-bottom:1px solid #e4e4e7;color:#09090b;font-size:14px;font-weight:700">${escapeHtml(input.cycle)}</td></tr><tr><td style="padding:15px 17px;color:#71717a;font-size:12px">Renewal</td><td align="right" style="padding:15px 17px;color:#09090b;font-size:12px;font-weight:700">No automatic renewal</td></tr></table>`;

const shell = (preview: string, eyebrow: string, title: string, content: string) => `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>@media only screen and (max-width:620px){.vxl-wrap{padding:16px 10px!important}.vxl-card{padding:24px 20px!important}.vxl-title{font-size:28px!important}.vxl-footer{padding:20px!important}}</style></head><body style="margin:0;padding:0;background:#f4f4f5;color:#18181b;font-family:Arial,Helvetica,sans-serif;-webkit-text-size-adjust:100%"><div style="display:none;max-height:0;overflow:hidden;opacity:0;color:transparent">${escapeHtml(preview)}</div><table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="background:#f4f4f5"><tr><td class="vxl-wrap" style="padding:38px 16px"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="max-width:600px;margin:0 auto"><tr><td class="vxl-card" style="padding:30px 34px 34px;border:1px solid #e4e4e7;border-radius:20px 20px 0 0;background:#ffffff">${logo}<div style="margin-top:35px;font-size:10px;line-height:1.4;letter-spacing:2px;color:#71717a;font-weight:800">${escapeHtml(eyebrow)}</div><h1 class="vxl-title" style="margin:10px 0 0;color:#09090b;font-size:34px;line-height:1.12;letter-spacing:-1.6px;font-weight:800">${escapeHtml(title)}</h1>${content}</td></tr><tr><td class="vxl-footer" style="padding:23px 34px;border-radius:0 0 20px 20px;background:#09090b;color:#a1a1aa;font-size:12px;line-height:1.7"><div style="color:#f4f4f5;font-weight:700">We Excel. We Grow Together.</div><div style="margin-top:5px">Questions? Reply to this email or write to <a href="mailto:${SUPPORT_EMAIL}" style="color:#ffffff;text-decoration:underline">${SUPPORT_EMAIL}</a>.</div><div style="margin-top:14px"><a href="${SITE_URL}/terms" style="color:#a1a1aa">Terms</a>&nbsp;&nbsp;·&nbsp;&nbsp;<a href="${SITE_URL}/privacy" style="color:#a1a1aa">Privacy</a>&nbsp;&nbsp;·&nbsp;&nbsp;<a href="${SITE_URL}/refund-policy" style="color:#a1a1aa">Refund policy</a></div><div style="margin-top:10px;color:#71717a">© 2026 VXL · thevxl.com</div></td></tr></table></td></tr></table></body></html>`;

export function planRequestReceivedEmail(input: PlanEmailInput) {
  const benefits = safeBenefits(input);
  const text = `Hi ${input.name},\n\nYour VXL ${input.plan} request has been recorded.\nPlan: VXL ${input.plan}\nPrice: ${input.amount}\nAccess period: ${input.cycle}\nRenewal: No automatic renewal\nRequest ID: ${input.requestId}\n${input.summary ? `\n${input.summary}\n` : ""}${benefitsText(benefits)}\nWe will review the request and send confirmed payment instructions to this email. Do not pay until you receive them. Never share an OTP, UPI PIN, password or card details.\n\nVXL support\n${SUPPORT_EMAIL}`;
  return { subject: `VXL ${input.plan} request received · ${input.requestId.slice(0, 8)}`, text, html: shell(`Your VXL ${input.plan} request is safely recorded.`, "PLAN REQUEST RECEIVED", `Your ${input.plan} request is in review.`, `<p style="margin:18px 0 0;color:#52525b;font-size:15px;line-height:1.75">Hi ${escapeHtml(input.name)}, we have safely recorded your request. Review the details below—nothing will be charged automatically.</p>${detailGrid(input)}${input.summary ? `<p style="margin:20px 0 0;color:#52525b;font-size:14px;line-height:1.7">${escapeHtml(input.summary)}</p>` : ""}${benefitsHtml(benefits)}<div style="margin-top:22px;padding:15px 17px;border-radius:12px;background:#09090b;color:#f4f4f5;font-family:monospace;font-size:12px;line-height:1.6"><span style="color:#a1a1aa">REQUEST ID</span><br>${escapeHtml(input.requestId)}</div><p style="margin:20px 0 0;color:#52525b;font-size:14px;line-height:1.7">We will review this request and email confirmed payment instructions. <strong>Do not pay until you receive them.</strong></p><p style="margin:14px 0 0;color:#71717a;font-size:12px;line-height:1.65">Fixed duration · does not renew automatically. VXL will never ask for your OTP, UPI PIN, password or complete card details.</p>`) };
}

export function paymentInstructionsEmail(input: PlanEmailInput & { upiId: string }) {
  const benefits = safeBenefits(input);
  const text = `Hi ${input.name},\n\nYour VXL ${input.plan} payment details are confirmed.\nPlan: VXL ${input.plan}\nPrice: ${input.amount}\nAccess period: ${input.cycle}\nRenewal: No automatic renewal\nUPI ID: ${input.upiId}\nRequest ID: ${input.requestId}\n${benefitsText(benefits)}\nHow to complete payment:\n1. Pay exactly ${input.amount} to the UPI ID above.\n2. Add ${input.requestId} to the payment note where possible.\n3. Reply to this email with the UPI transaction reference.\n\nWe verify the payment independently before issuing your account-bound, single-use activation code. Never share an OTP, UPI PIN, password or card details.\n\nVXL support\n${SUPPORT_EMAIL}`;
  return { subject: `Payment instructions · VXL ${input.plan} · ${input.amount}`, text, html: shell(`Confirmed payment instructions for VXL ${input.plan}.`, "PAYMENT INSTRUCTIONS", `Your ${input.plan} details are confirmed.`, `<p style="margin:18px 0 0;color:#52525b;font-size:15px;line-height:1.75">Hi ${escapeHtml(input.name)}, check the plan, price and duration before proceeding.</p>${detailGrid(input)}<div style="margin:22px 0 0;padding:22px;border-radius:14px;background:#09090b;color:#ffffff"><div style="font-size:10px;letter-spacing:1.8px;color:#a1a1aa;font-weight:800">PAY EXACTLY</div><div style="margin-top:7px;font-size:30px;font-weight:800;letter-spacing:-1px">${escapeHtml(input.amount)}</div><div style="margin-top:17px;padding-top:15px;border-top:1px solid #27272a;font-size:12px;color:#a1a1aa">UPI ID</div><div style="margin-top:5px;font-family:monospace;font-size:16px;color:#ffffff;overflow-wrap:anywhere">${escapeHtml(input.upiId)}</div></div><div style="margin-top:24px"><div style="font-size:10px;letter-spacing:1.8px;color:#71717a;font-weight:800">COMPLETE IN 3 STEPS</div><ol style="margin:12px 0 0;padding-left:20px;color:#3f3f46;font-size:14px;line-height:1.75"><li>Pay exactly <strong>${escapeHtml(input.amount)}</strong> to the UPI ID above.</li><li>Add your request ID to the payment note where possible.</li><li>Reply to this email with the UPI transaction reference.</li></ol></div><div style="margin-top:18px;padding:14px 16px;border:1px solid #e4e4e7;border-radius:11px;color:#52525b;font-family:monospace;font-size:11px;line-height:1.55;overflow-wrap:anywhere"><span style="color:#71717a">REQUEST ID</span><br>${escapeHtml(input.requestId)}</div>${benefitsHtml(benefits)}<p style="margin:18px 0 0;color:#71717a;font-size:12px;line-height:1.65">We verify every payment independently before issuing an account-bound, single-use activation code. Never share an OTP, UPI PIN, password or complete card details.</p>`) };
}

export function activationCodeEmail(input: PlanEmailInput & { code: string; expiresAt: string }) {
  const benefits = safeBenefits(input);
  const text = `Hi ${input.name},\n\nPayment verified. Your VXL ${input.plan} activation code is ready.\nPlan: VXL ${input.plan}\nPrice paid: ${input.amount}\nAccess period: ${input.cycle}\nRenewal: No automatic renewal\n\nActivation code: ${input.code}\nCode expires: ${input.expiresAt}\nRequest ID: ${input.requestId}\n${benefitsText(benefits)}\nOpen VXL → Plans, enter this code and select Activate plan. The code is bound to your account and can be used once.\n\nVXL support\n${SUPPORT_EMAIL}`;
  return { subject: `Payment verified · Activate VXL ${input.plan}`, text, html: shell(`Payment verified. Your private VXL ${input.plan} activation code is ready.`, "PAYMENT VERIFIED", `Your ${input.plan} plan is ready to activate.`, `<p style="margin:18px 0 0;color:#52525b;font-size:15px;line-height:1.75">Hi ${escapeHtml(input.name)}, your payment has been verified. Use the private code below to activate your plan.</p><div style="margin:24px 0 0;padding:25px 18px;border-radius:15px;background:#09090b;text-align:center;color:#ffffff"><div style="font-size:10px;letter-spacing:2px;color:#a1a1aa;font-weight:800">SINGLE-USE ACTIVATION CODE</div><div style="margin-top:12px;font-family:monospace;font-size:29px;font-weight:700;letter-spacing:3px;overflow-wrap:anywhere">${escapeHtml(input.code)}</div><div style="margin-top:12px;color:#a1a1aa;font-size:11px">Expires ${escapeHtml(input.expiresAt)}</div></div>${detailGrid(input)}<a href="${SITE_URL}" style="display:block;margin:24px 0 0;padding:15px 18px;border-radius:11px;background:#09090b;color:#ffffff;text-align:center;text-decoration:none;font-size:14px;font-weight:800">Open VXL and activate</a><p style="margin:18px 0 0;color:#52525b;font-size:14px;line-height:1.7">Go to <strong>Plans</strong>, enter the code, then select <strong>Activate plan</strong>. The code is bound to your account and works once.</p>${benefitsHtml(benefits)}<p style="margin:18px 0 0;color:#71717a;font-size:12px;line-height:1.65">Request ${escapeHtml(input.requestId)} · Keep this code private. VXL will never ask for your OTP, UPI PIN or password.</p>`) };
}

export function expiryReminderEmail(input: { name: string; plan: string; endsAt: string; daysRemaining: number; isTrial: boolean }) {
  const plan = input.isTrial ? "free trial" : `VXL ${input.plan}`;
  const expired = input.daysRemaining <= 0;
  const timing = expired ? "has ended" : `ends in ${input.daysRemaining} day${input.daysRemaining === 1 ? "" : "s"}`;
  const action = input.isTrial ? "Choose Live, Flex or Care to bring your portfolio back online whenever you are ready." : "Choose your plan again to continue without automatic renewal.";
  const text = `Hi ${input.name},\n\nYour ${plan} ${timing}.\nAccess end: ${input.endsAt}\n\n${action}\n\nYour profile and private draft remain safely saved. VXL never renews or charges automatically.\n\nOpen VXL: ${SITE_URL}\n\nVXL support\n${SUPPORT_EMAIL}`;
  return {
    subject: expired ? `Your ${plan} has ended` : `Your ${plan} ${timing}`,
    text,
    html: shell(`Your ${plan} ${timing}.`, expired ? "ACCESS PERIOD ENDED" : "EXPIRY REMINDER", `Your ${plan} ${timing}.`, `<p style="margin:18px 0 0;color:#52525b;font-size:15px;line-height:1.75">Hi ${escapeHtml(input.name)}, this is a clear reminder before your access changes.</p><div style="margin:24px 0 0;padding:22px;border-radius:14px;background:#09090b;color:#ffffff"><div style="font-size:10px;letter-spacing:1.8px;color:#a1a1aa;font-weight:800">ACCESS ${expired ? "ENDED" : "ENDS"}</div><div style="margin-top:8px;font-size:24px;font-weight:800">${escapeHtml(input.endsAt)}</div><div style="margin-top:8px;color:#a1a1aa;font-size:12px">No automatic renewal · no automatic charge</div></div><p style="margin:20px 0 0;color:#52525b;font-size:14px;line-height:1.7">${escapeHtml(action)}</p><a href="${SITE_URL}" style="display:block;margin:24px 0 0;padding:15px 18px;border-radius:11px;background:#09090b;color:#ffffff;text-align:center;text-decoration:none;font-size:14px;font-weight:800">Open VXL plans</a><p style="margin:18px 0 0;color:#71717a;font-size:12px;line-height:1.65">Your profile and private draft remain safely saved even after access ends.</p>`),
  };
}
