import type { Metadata } from "next";import { LegalShell,type LegalSection } from "@/app/legal-shell";
export const metadata:Metadata={title:"VXL Refund & Cancellation Policy",description:"Refund and cancellation conditions for VXL digital services."};
const sections:LegalSection[]=[
{title:"Digital Services",paragraphs:["VXL provides digital/software services. Paid features may become available shortly after successful payment and subscription activation.","Because digital Services can be made available immediately, refunds are not automatically available merely because a user changes their mind after successfully receiving access.","Nothing in this policy limits any refund or remedy that must be provided under applicable law."]},
{title:"Eligible Refund Situations",paragraphs:["A refund may be considered where:"],bullets:["the user's account was charged more than once for the same intended purchase;","payment was successfully collected but the purchased subscription was not activated because of a technical failure attributable to VXL;","an incorrect amount was charged because of a VXL or payment-processing error;","another circumstance requires a refund under applicable law.","Where an activation problem can reasonably be corrected, VXL may first attempt to restore the purchased access."]},
{title:"Non-Refundable Situations",paragraphs:["Subject to applicable law, refunds will generally not be provided where:"],bullets:["the user simply changes their mind after paid access has been provided;","the user did not use the subscription after purchasing it;","the user purchased the wrong plan despite the applicable plan and price being clearly displayed;","access is restricted because of material misuse, fraud or violation of VXL's Terms;","the request relates to circumstances outside VXL's control and the purchased Service was correctly provided."]},
{title:"Requesting a Refund",paragraphs:["To request a refund, contact VXL through the Contact Us page and provide:"],bullets:["the email address associated with the VXL account;","transaction/payment reference;","date and amount of payment;","plan purchased;","reason for the request.","Refund requests should preferably be submitted within 7 days of the relevant transaction so that they can be investigated promptly.","This 7-day request period does not override any longer statutory right that may apply under law."]},
{title:"Refund Review",paragraphs:["Refund requests are reviewed individually.","We may request additional information reasonably necessary to verify the transaction and circumstances."]},
{title:"Refund Processing",paragraphs:["Where a refund is approved, VXL will initiate it to the original payment method where reasonably possible.","After initiation, the time taken for funds to appear depends on the payment provider, bank, card network or UPI provider.","VXL cannot guarantee the processing time of third-party financial institutions after a refund has been successfully initiated."]},
{title:"Cancellation of Fixed-Term Plans",paragraphs:["For non-recurring fixed-duration plans, users may choose not to renew the plan. Access will ordinarily continue until the end of the already-paid subscription period.","Unused time is not automatically refundable unless required by law or specifically approved under this policy."]},
{title:"Recurring Subscriptions",paragraphs:["If VXL offers recurring subscriptions, users will be provided with a method to cancel future renewals.","Cancellation stops future recurring charges but does not ordinarily result in a refund for a billing period that has already begun, unless required by applicable law or otherwise stated at purchase."]},
{title:"Failed or Pending Payments",paragraphs:["If a payment fails but money appears to have been debited, users should not immediately make repeated payments without checking the payment status.","Banks and payment providers may automatically reverse failed transactions.","Users can contact VXL if the transaction remains unresolved."]},
{title:"Duplicate Payments",paragraphs:["Verified duplicate payments for the same intended purchase may be refunded after transaction verification."]},
{title:"Contact",paragraphs:["Questions or refund requests can be submitted through the VXL Contact Us page."]}];
export default function RefundPage(){return <LegalShell title="Refund & Cancellation Policy" intro={["This Refund & Cancellation Policy applies to paid digital Services purchased through VXL."]} sections={sections}/>}
