"use client";

import { useCallback, useEffect, useMemo, useState } from "react";

type Customer = { id:string; full_name:string; email:string; portfolio_slug:string; is_public:boolean };
type Purchase = { id:string; mode:string; plan:string; billing_cycle:string; amount_paise:number; razorpay_payment_id:string|null; status:string; activated_at:string|null; period_ends_at:string|null; created_at:string; customer:Customer|null };
type Subscription = { profile_id:string; plan:string; status:string; period_starts_at:string|null; period_ends_at:string|null; customer:Customer|null };
type Webhook = { event_id:string; event_type:string; payment_id:string; mode:string; status:string; delivery_count:number; received_at:string; last_error_category:string|null };
type Email = { id:string; email_to:string; subject:string; status:string; attempts:number; max_attempts:number; created_at:string; sent_at:string|null; last_error_code:string|null };
type Data = { summary:{liveRevenuePaise:number;capturedPayments:number;activeSubscriptions:number;failedWebhooks:number;pendingEmails:number}; purchases:Purchase[]; subscriptions:Subscription[]; webhookEvents:Webhook[]; emailJobs:Email[] };
type Tab = "payments"|"subscriptions"|"webhooks"|"emails";
const initial:Data={summary:{liveRevenuePaise:0,capturedPayments:0,activeSubscriptions:0,failedWebhooks:0,pendingEmails:0},purchases:[],subscriptions:[],webhookEvents:[],emailJobs:[]};
const cash=(p:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(p/100);
const when=(v?:string|null)=>v?new Intl.DateTimeFormat("en-IN",{dateStyle:"medium",timeStyle:"short"}).format(new Date(v)):"—";
const short=(v?:string|null)=>v?`${v.slice(0,12)}…${v.slice(-5)}`:"—";

function Pill({value}:{value:string}){const good=["captured","active","processed","sent"].includes(value),bad=["failed","expired","cancelled"].includes(value);return <span className={`rounded-full px-2.5 py-1 text-xs font-bold ring-1 ring-inset ${good?"bg-emerald-50 text-emerald-800 ring-emerald-200":bad?"bg-rose-50 text-rose-800 ring-rose-200":"bg-amber-50 text-amber-800 ring-amber-200"}`}>{value.replaceAll("_"," ")}</span>}
function Empty(){return <div className="p-12 text-center text-slate-500">No records in this view.</div>}

export function AdminBillingDashboard({adminEmail}:{adminEmail:string}){
  const [data,setData]=useState<Data>(initial),[tab,setTab]=useState<Tab>("payments"),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null);
  const load=useCallback(async()=>{setLoading(true);setError(null);try{const r=await fetch("/api/admin/billing",{cache:"no-store"}),body=await r.json();if(!r.ok)throw new Error(body.error||"Could not load operations.");setData(body)}catch(e){setError(e instanceof Error?e.message:"Could not load operations.")}finally{setLoading(false)}},[]);
  useEffect(()=>{const task=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(task)},[load]);
  const attention=data.summary.failedWebhooks+data.summary.pendingEmails;
  const cards=useMemo(()=>[["Live revenue",cash(data.summary.liveRevenuePaise),"Captured production payments"],["Payments",String(data.summary.capturedPayments),"Successfully captured"],["Active plans",String(data.summary.activeSubscriptions),"Access active today"],["Needs attention",String(attention),attention?"Review failures below":"Operations healthy"]],[data,attention]);
  return <main className="min-h-screen bg-[#f5f6fb] px-4 py-8 text-slate-950 sm:px-8"><div className="mx-auto max-w-7xl">
    <header className="overflow-hidden rounded-[2rem] bg-[radial-gradient(circle_at_80%_0%,rgba(34,211,238,.25),transparent_38%),linear-gradient(135deg,#09090b,#312e81)] px-6 py-8 text-white shadow-2xl shadow-indigo-950/15 sm:px-10"><div className="flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[.24em] text-indigo-200">VXL private operations</p><h1 className="mt-3 text-3xl font-black tracking-tight sm:text-5xl">Every customer. One clear view.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-indigo-100 sm:text-base">Live Razorpay payments, access, webhook health and transactional email delivery.</p></div><div className="rounded-2xl border border-white/15 bg-white/10 px-4 py-3 text-sm backdrop-blur">Owner · <b>{adminEmail}</b></div></div></header>
    <section className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([l,v,d])=><div key={l} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-sm font-medium text-slate-500">{l}</p><p className="mt-1 text-3xl font-black tracking-tight">{v}</p><p className="mt-2 text-xs text-slate-400">{d}</p></div>)}</section>
    <section className="mt-6 overflow-hidden rounded-[2rem] border border-slate-200 bg-white shadow-sm"><div className="flex flex-col justify-between gap-3 border-b border-slate-200 p-4 sm:flex-row sm:items-center sm:p-6"><div className="flex flex-wrap gap-2">{(["payments","subscriptions","webhooks","emails"] as Tab[]).map(x=><button key={x} onClick={()=>setTab(x)} className={`rounded-full px-4 py-2 text-sm font-semibold capitalize ${tab===x?"bg-slate-950 text-white":"bg-slate-100 text-slate-600 hover:bg-slate-200"}`}>{x}{x==="webhooks"&&data.summary.failedWebhooks?` (${data.summary.failedWebhooks})`:""}{x==="emails"&&data.summary.pendingEmails?` (${data.summary.pendingEmails})`:""}</button>)}</div><button onClick={()=>void load()} disabled={loading} className="rounded-xl border border-slate-200 px-4 py-2 text-sm font-semibold text-slate-700 hover:bg-slate-50 disabled:opacity-50">{loading?"Refreshing…":"Refresh"}</button></div>
      {error?<div className="m-6 rounded-2xl bg-rose-50 p-5 text-sm font-semibold text-rose-800">{error}</div>:<div className="overflow-x-auto">
        {tab==="payments"&&(data.purchases.length?<table className="w-full min-w-[900px] text-left text-sm"><thead><tr>{["Customer","Plan","Amount","State","Razorpay payment","Activated","Access until"].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{data.purchases.map(x=><tr key={x.id}><td><b>{x.customer?.full_name||"VXL member"}</b><small>{x.customer?.email||x.id}</small></td><td><b>{x.plan.toUpperCase()}</b><small>{x.billing_cycle.replace("_"," ")} · {x.mode}</small></td><td><b>{cash(x.amount_paise)}</b></td><td><Pill value={x.status}/></td><td className="font-mono text-xs" title={x.razorpay_payment_id||""}>{short(x.razorpay_payment_id)}</td><td>{when(x.activated_at)}</td><td>{when(x.period_ends_at)}</td></tr>)}</tbody></table>:<Empty/>)}
        {tab==="subscriptions"&&(data.subscriptions.length?<table className="w-full min-w-[760px] text-left text-sm"><thead><tr>{["Customer","Portfolio","Plan","State","Started","Expires"].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{data.subscriptions.map(x=><tr key={x.profile_id}><td><b>{x.customer?.full_name||"VXL member"}</b><small>{x.customer?.email||x.profile_id}</small></td><td>{x.customer?.portfolio_slug||"—"}<small>{x.customer?.is_public?"Published":"Draft"}</small></td><td><b>{x.plan.toUpperCase()}</b></td><td><Pill value={x.status}/></td><td>{when(x.period_starts_at)}</td><td>{when(x.period_ends_at)}</td></tr>)}</tbody></table>:<Empty/>)}
        {tab==="webhooks"&&(data.webhookEvents.length?<table className="w-full min-w-[850px] text-left text-sm"><thead><tr>{["Received","Event","State","Payment","Mode","Deliveries","Error"].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{data.webhookEvents.map(x=><tr key={x.event_id}><td>{when(x.received_at)}</td><td><b>{x.event_type}</b></td><td><Pill value={x.status}/></td><td className="font-mono text-xs" title={x.payment_id}>{short(x.payment_id)}</td><td>{x.mode.toUpperCase()}</td><td>{x.delivery_count}</td><td className="text-rose-700">{x.last_error_category||"—"}</td></tr>)}</tbody></table>:<Empty/>)}
        {tab==="emails"&&(data.emailJobs.length?<table className="w-full min-w-[900px] text-left text-sm"><thead><tr>{["Created","Recipient","Subject","State","Attempts","Sent","Error"].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{data.emailJobs.map(x=><tr key={x.id}><td>{when(x.created_at)}</td><td>{x.email_to}</td><td className="max-w-xs truncate" title={x.subject}><b>{x.subject}</b></td><td><Pill value={x.status}/></td><td>{x.attempts}/{x.max_attempts}</td><td>{when(x.sent_at)}</td><td className="text-rose-700">{x.last_error_code||"—"}</td></tr>)}</tbody></table>:<Empty/>)}
      </div>}
    </section><p className="mx-auto mt-5 max-w-3xl text-center text-xs leading-5 text-slate-500">Read-only operations view. Paid access remains controlled only by verified Razorpay capture and the idempotent subscription transaction.</p>
  </div><style jsx>{`thead{background:#f8fafc;color:#64748b;font-size:.75rem;text-transform:uppercase;letter-spacing:.04em}th,td{padding:1rem 1.25rem}tbody tr{border-top:1px solid #f1f5f9}td small{display:block;margin-top:.2rem;color:#64748b;font-size:.75rem;font-weight:400}`}</style></main>
}
